var reddit = window.reddit = window.reddit || {};


reddit.ActionTypes = {
	RECEIVE_RAW_SUBREDDITS: 'RECEIVE_RAW_SUBREDDITS',
	RECEIVE_RAW_POSTS: 'RECEIVE_RAW_POSTS',
	RECEIVE_RAW_COMMENTS: 'RECEIVE_RAW_COMMENTS'
};